### ISSUE TITLE
System.IO.FileNotFoundException @ Terraria.exe

### ISSUE THREAD

**Issue by mz2212** [BobTheBob9/Terraria1.4UltrawidePatcher#1]
Thanks for making a project to do this so early after the release of 1.4.  
I'm attempting to run this in an elevated command prompt and get this error:

```
C:\Program Files (x86)\Steam\steamapps\common\Terraria>Terraria1.4UltrawidePatcher.exe "C:\Program Files (x86)\Steam\steamapps\common\Terraria\Terraria.exe"

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'E:\SteamLibrary\steamapps\common\Terraria\Terraria.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at TerrariaUltrawidePatcher.Program.Main(String[] args) in C:\Users\bobthebob\source\repos\Terraria1.4UltrawidePatcher\Terraria1.4UltrawidePatcher\Program.cs:line 23
```

From my looking through the repo, I can't even find a mention of that file location and it should in fact be working as expected.  
Do you think it could be fixed if I build the project on my machine?

**Comment by LCrucio** [comment]
I'd do that, I built it and it works perfectly. Thanks Bob for saving me time ILSpying Terraria!

**Comment by mz2212** [comment]
@clansfear That worked!
The fix for this bug is to build as release, then it works as expected.

Thanks again bob!

**Comment by BobTheBob9** [comment]
could've been something i left in by accident, will upload a new build quick
